services:
  pytest_runner:
    image: tests
    build: .
    volumes:
      - .:/test_project
    command: /bin/sh -c "pytest --browser_name=chrome -v --alluredir=allure_results/"

  report:
    image: tests
    build: .
    volumes:
      - .:/test_project
    command: /bin/sh -c "allure generate allure_results --clean -o allure_report"